version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /test/Dockstore.cwl
     testParameterFiles:
     - /test/dockstore.cwl.json
   - name: Natalie
     role: dev
     affiliation: UCSC
   - name: UCSC Genomics Institute
     role: Institute
     affiliation: UCSC
